### PR TITLE
fix(a11y): change payment dropdown trigger to button with accessible label (fixes #336)

### LINKED ISSUE #336: default payments accessibility
https://github.com/j2commerce/j2commerce/blob/4268fc7ad380a2d14269527632e16dcb14d80008/components/com_j2commerce/tmpl/myprofile/default_payment_methods.php#L75-L77

This link should be a button and have some text (even hidden)

### PR DESCRIPTION
**Pull request by newlinewebdesign**
## Summary
Fixes #336

## Changes
- Changed `<a role="button">` to `<button type="button">` for the payment method dropdown trigger
- Added `aria-label` using existing `COM_J2COMMERCE_ACTIONS` language string
- Added `aria-hidden="true"` on the icon
- Added `<span class="visually-hidden">` with "Actions" text for screen readers

## Testing
1. Navigate to frontend My Profile → Payment Methods
2. Verify dropdown trigger is a `<button>` element (inspect)
3. Verify dropdown still opens on click
4. Verify screen reader announces "Actions"

## Files Changed
- `components/com_j2commerce/tmpl/myprofile/default_payment_methods.php` — a11y fix on dropdown trigger

### CODE REVIEW

**Comment by brianteeman** [comment]
Did you intend to delete the build script

**Comment by newlinewebdesign** [comment]
not from my local machine, but I suppose this should allow any of us to create the new package so I see why it could bring value in the repo

File: components/com_j2commerce/tmpl/myprofile/default_payment_methods.php [hunk 1]
```diff
@@ -72,9 +72,10 @@
                                         </div>
                                         <div class="d-flex align-items-center">
                                         <span class="dropdown dropstart">
-                                           <a role="button" class="text-reset dropdown-toggle" href="#" id="paymentDropdown<?php echo htmlspecialchars($method->id, ENT_QUOTES, 'UTF-8'); ?>" data-bs-toggle="dropdown" data-bs-offset="-20,20" aria-expanded="false">
-                                              <span class="fa-solid fa-ellipsis-vertical"></span>
-                                           </a>
+                                           <button type="button" class="btn btn-link text-reset dropdown-toggle p-0" id="paymentDropdown<?php echo htmlspecialchars($method->id, ENT_QUOTES, 'UTF-8'); ?>" data-bs-toggle="dropdown" data-bs-offset="-20,20" aria-expanded="false" aria-label="<?php echo Text::_('COM_J2COMMERCE_ACTIONS'); ?>">
```
Comment (brianteeman) [inline components/com_j2commerce/tmpl/myprofile/default_payment_methods.php:75]: its only an ID which is a number so no need for the htmlspecialchars

File: components/com_j2commerce/tmpl/myprofile/default_payment_methods.php [hunk 2]
```diff
@@ -72,9 +72,10 @@
...
+                                              <span class="fa-solid fa-ellipsis-vertical" aria-hidden="true"></span>
+                                              <span class="visually-hidden"><?php echo Text::_('COM_J2COMMERCE_ACTIONS'); ?></span>
```
Comment (brianteeman) [inline components/com_j2commerce/tmpl/myprofile/default_payment_methods.php:77]: no need for this line as the button already has an aria-label

File: components/com_j2commerce/tmpl/myprofile/default_payment_methods.php (hunk 1 above)
Comment (brianteeman) [reply components/com_j2commerce/tmpl/myprofile/default_payment_methods.php:75]: probably needs fixing throoughout the file
